begin;
-- Hungarian TEAOR 2008 Complete list, 2014-02-03
-- by István Pongrácz, StartIT Kft. www.startit.hu
-- contact: pongracz.istvan@gmail.com pongracz.istvan@startit.hu
INSERT INTO sic (code, sictype,description) VALUES ('16', 'H', 'Fafeldolgozás (kivéve: bútor), fonottáru gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('46', 'H', 'Nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('47', 'H', 'Kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('64', 'H', 'Pénzügyi közvetítés');
INSERT INTO sic (code, sictype,description) VALUES ('65', 'H', 'Biztosítás, viszontbiztosítás, nyugdíjalapok (kivéve: kötelező társadalombiztosítás)');
INSERT INTO sic (code, sictype,description) VALUES ('111', '', 'Gabonaféle (kivéve: rizs), hüvelyes növény, olajos mag termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('141', 'H', 'Ruházat gyártása (kivéve: szőrmeruházat)');
INSERT INTO sic (code, sictype,description) VALUES ('531', 'H', 'Postai tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('642', 'H', 'Vagyonkezelés');
INSERT INTO sic (code, sictype,description) VALUES ('661', 'H', 'Pénzügyi kiegészítő tevékenység (kivéve: biztosítás, nyugdíjalap)');
INSERT INTO sic (code, sictype,description) VALUES ('1392', '', 'Konfekcionált textiláru gyártása (kivéve: ruházat)');
INSERT INTO sic (code, sictype,description) VALUES ('1395', '', 'Nem szőtt textília és termék gyártása (kivéve: ruházat)');
INSERT INTO sic (code, sictype,description) VALUES ('1413', '', 'Felsőruházat gyártása (kivéve: munkaruházat)');
INSERT INTO sic (code, sictype,description) VALUES ('1812', '', 'Nyomás (kivéve: napilap)');
INSERT INTO sic (code, sictype,description) VALUES ('2811', '', 'Motor, turbina gyártása (kivéve: légi-, közútijármű-motor)');
INSERT INTO sic (code, sictype,description) VALUES ('2823', '', 'Irodagép gyártása (kivéve: számítógép és perifériái)');
INSERT INTO sic (code, sictype,description) VALUES ('5310', '', '5310 Postai tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('6420', '', '6420 Vagyonkezelés');
INSERT INTO sic (code, sictype,description) VALUES ('7712', '', 'Gépjárműkölcsönzés (3,5 tonna fölött)');
INSERT INTO sic (code, sictype,description) VALUES ('7733', '', 'Irodagép kölcsönzése (beleértve: számítógép)');
INSERT INTO sic (code, sictype,description) VALUES ('8412', '', 'Egészségügy, oktatás, kultúra, egyéb szociális szolgáltatás (kivéve: társadalombiztosítás) igazgatása');
INSERT INTO sic (code, sictype,description) VALUES ('01', 'H', 'Növénytermesztés, állattenyésztés, vadgazdálkodás és kapcsolódó szolgáltatások');
INSERT INTO sic (code, sictype,description) VALUES ('011', 'H', 'Nem évelő növény termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('0112', '', 'Rizstermesztés');
INSERT INTO sic (code, sictype,description) VALUES ('0113', '', 'Zöldségféle, dinnye, gyökér-, gumósnövény termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('0114', '', 'Cukornádtermesztés');
INSERT INTO sic (code, sictype,description) VALUES ('0115', '', 'Dohánytermesztés');
INSERT INTO sic (code, sictype,description) VALUES ('0116', '', 'Rostnövénytermesztés');
INSERT INTO sic (code, sictype,description) VALUES ('0119', '', 'Egyéb, nem évelő növény termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('012', 'H', 'Évelő növény termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('0121', '', 'Szőlőtermesztés');
INSERT INTO sic (code, sictype,description) VALUES ('0122', '', 'Trópusi gyümölcs termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('0123', '', 'Citrusféle termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('0124', '', 'Almatermésű, csonthéjas termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('0125', '', 'Egyéb gyümölcs, héjastermésű termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('0126', '', 'Olajtartalmú gyümölcs termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('0127', '', 'Italgyártási növény termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('0128', '', 'Fűszer-, aroma-, narkotikus, gyógynövény termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('0129', '', 'Egyéb évelő növény termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('013', 'H', 'Növényi szaporítóanyag termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('0130', '', 'Növényi szaporítóanyag termesztése');
INSERT INTO sic (code, sictype,description) VALUES ('014', 'H', 'Állattenyésztés');
INSERT INTO sic (code, sictype,description) VALUES ('0141', '', 'Tejhasznú szarvasmarha tenyésztése');
INSERT INTO sic (code, sictype,description) VALUES ('0142', '', 'Egyéb szarvasmarha tenyésztése');
INSERT INTO sic (code, sictype,description) VALUES ('0143', '', 'Ló, lóféle tenyésztése');
INSERT INTO sic (code, sictype,description) VALUES ('0144', '', 'Teve, teveféle tenyésztése');
INSERT INTO sic (code, sictype,description) VALUES ('0145', '', 'Juh, kecske tenyésztése');
INSERT INTO sic (code, sictype,description) VALUES ('0146', '', 'Sertéstenyésztés');
INSERT INTO sic (code, sictype,description) VALUES ('0147', '', 'Baromfitenyésztés');
INSERT INTO sic (code, sictype,description) VALUES ('0149', '', 'Egyéb állat tenyésztése');
INSERT INTO sic (code, sictype,description) VALUES ('015', 'H', 'Vegyes gazdálkodás');
INSERT INTO sic (code, sictype,description) VALUES ('0150', '', 'Vegyes gazdálkodás');
INSERT INTO sic (code, sictype,description) VALUES ('016', 'H', 'Mezőgazdasági, betakarítást követő szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('0161', '', 'Növénytermesztési szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('0162', '', 'Állattenyésztési szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('0163', '', 'Betakarítást követő szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('0164', '', 'Vetési célú magfeldolgozás');
INSERT INTO sic (code, sictype,description) VALUES ('017', 'H', 'Vadgazdálkodás, vadgazdálkodási szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('0170', '', 'Vadgazdálkodás, vadgazdálkodási szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('02', 'H', 'Erdőgazdálkodás');
INSERT INTO sic (code, sictype,description) VALUES ('021', 'H', 'Erdészeti, egyéb erdőgazdálkodási tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('0210', '', 'Erdészeti, egyéb erdőgazdálkodási tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('022', 'H', 'Fakitermelés');
INSERT INTO sic (code, sictype,description) VALUES ('0220', '', 'Fakitermelés');
INSERT INTO sic (code, sictype,description) VALUES ('023', 'H', 'Vadon termő egyéb erdei termék gyűjtése');
INSERT INTO sic (code, sictype,description) VALUES ('0230', '', 'Vadon termő egyéb erdei termék gyűjtése');
INSERT INTO sic (code, sictype,description) VALUES ('024', 'H', 'Erdészeti szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('0240', '', 'Erdészeti szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('03', 'H', 'Halászat, halgazdálkodás');
INSERT INTO sic (code, sictype,description) VALUES ('031', 'H', 'Halászat');
INSERT INTO sic (code, sictype,description) VALUES ('0311', '', 'Tengeri halászat');
INSERT INTO sic (code, sictype,description) VALUES ('0312', '', 'Édesvízi halászat');
INSERT INTO sic (code, sictype,description) VALUES ('032', 'H', 'Halgazdálkodás');
INSERT INTO sic (code, sictype,description) VALUES ('0321', '', 'Tengerihal-gazdálkodás');
INSERT INTO sic (code, sictype,description) VALUES ('0322', '', 'Édesvízihal-gazdálkodás');
INSERT INTO sic (code, sictype,description) VALUES ('05', 'H', 'Szénbányászat');
INSERT INTO sic (code, sictype,description) VALUES ('051', 'H', 'Feketeszén-bányászat');
INSERT INTO sic (code, sictype,description) VALUES ('0510', '', 'Feketeszén-bányászat');
INSERT INTO sic (code, sictype,description) VALUES ('052', 'H', 'Barnaszén-, lignitbányászat');
INSERT INTO sic (code, sictype,description) VALUES ('0520', '', 'Barnaszén-, lignitbányászat');
INSERT INTO sic (code, sictype,description) VALUES ('06', 'H', 'Kőolaj-, földgázkitermelés');
INSERT INTO sic (code, sictype,description) VALUES ('061', 'H', 'Kőolaj-kitermelés');
INSERT INTO sic (code, sictype,description) VALUES ('0610', '', 'Kőolaj-kitermelés');
INSERT INTO sic (code, sictype,description) VALUES ('062', 'H', 'Földgázkitermelés');
INSERT INTO sic (code, sictype,description) VALUES ('0620', '', 'Földgázkitermelés');
INSERT INTO sic (code, sictype,description) VALUES ('07', 'H', 'Fémtartalmú érc bányászata');
INSERT INTO sic (code, sictype,description) VALUES ('071', 'H', 'Vasércbányászat');
INSERT INTO sic (code, sictype,description) VALUES ('0710', '', 'Vasércbányászat');
INSERT INTO sic (code, sictype,description) VALUES ('072', 'H', 'Egyéb fém érc bányászata');
INSERT INTO sic (code, sictype,description) VALUES ('0721', '', 'Urán-, tóriumérc-bányászat');
INSERT INTO sic (code, sictype,description) VALUES ('0729', '', 'Színesfém érc bányászata');
INSERT INTO sic (code, sictype,description) VALUES ('08', 'H', 'Egyéb bányászat');
INSERT INTO sic (code, sictype,description) VALUES ('081', 'H', 'Kőfejtés, homok-, agyagbányászat');
INSERT INTO sic (code, sictype,description) VALUES ('0811', '', 'Kőfejtés, gipsz, kréta bányászata');
INSERT INTO sic (code, sictype,description) VALUES ('0812', '', 'Kavics-, homok-, agyagbányászat');
INSERT INTO sic (code, sictype,description) VALUES ('089', 'H', 'Mns bányászat');
INSERT INTO sic (code, sictype,description) VALUES ('0891', '', 'Vegyi ásvány bányászata');
INSERT INTO sic (code, sictype,description) VALUES ('0892', '', 'Tőzegkitermelés');
INSERT INTO sic (code, sictype,description) VALUES ('0893', '', 'Sókitermelés');
INSERT INTO sic (code, sictype,description) VALUES ('0899', '', 'Egyéb mns bányászat');
INSERT INTO sic (code, sictype,description) VALUES ('09', 'H', 'Bányászati szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('091', 'H', 'Kőolaj-, földgáz-kitermelési szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('0910', '', 'Kőolaj-, földgáz-kitermelési szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('099', 'H', 'Egyéb bányászati szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('0990', '', 'Egyéb bányászati szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('10', 'H', 'Élelmiszergyártás');
INSERT INTO sic (code, sictype,description) VALUES ('101', 'H', 'Húsfeldolgozás, -tartósítás, húskészítmény gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1011', '', 'Húsfeldolgozás, -tartósítás');
INSERT INTO sic (code, sictype,description) VALUES ('1012', '', 'Baromfihús feldolgozása, tartósítása');
INSERT INTO sic (code, sictype,description) VALUES ('1013', '', 'Hús-, baromfihús-készítmény gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('102', 'H', 'Halfeldolgozás, -tartósítás');
INSERT INTO sic (code, sictype,description) VALUES ('1020', '', 'Halfeldolgozás, -tartósítás');
INSERT INTO sic (code, sictype,description) VALUES ('103', 'H', 'Gyümölcs-, zöldségfeldolgozás, -tartósítás');
INSERT INTO sic (code, sictype,description) VALUES ('1031', '', 'Burgonyafeldolgozás, -tartósítás');
INSERT INTO sic (code, sictype,description) VALUES ('1032', '', 'Gyümölcs-, zöldséglé gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1039', '', 'Egyéb gyümölcs-, zöldségfeldolgozás, -tartósítás');
INSERT INTO sic (code, sictype,description) VALUES ('104', 'H', 'Növényi, állati olaj gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1041', '', 'Olaj gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1042', '', 'Margarin gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('105', 'H', 'Tejfeldolgozás');
INSERT INTO sic (code, sictype,description) VALUES ('1051', '', 'Tejtermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1052', '', 'Jégkrém gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('106', 'H', 'Malomipari termék, keményítő gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1061', '', 'Malomipari termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1062', '', 'Keményítő, keményítőtermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('107', 'H', 'Pékáru, tésztafélék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1071', '', 'Kenyér; friss pékáru gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1072', '', 'Tartósított lisztes áru gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1073', '', 'Tésztafélék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('108', 'H', 'Egyéb élelmiszer gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1081', '', 'Cukorgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('1082', '', 'Édesség gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1083', '', 'Tea, kávé feldolgozása');
INSERT INTO sic (code, sictype,description) VALUES ('1084', '', 'Fűszer, ételízesítő gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1085', '', 'Készétel gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1086', '', 'Homogenizált, diétás étel gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1089', '', 'Mns egyéb élelmiszer gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('109', 'H', 'Takarmány gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1091', '', 'Haszonállat-eledel gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1092', '', 'Hobbiállat-eledel gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('11', 'H', 'Italgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('110', 'H', 'Italgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('1101', '', 'Desztillált szeszes ital gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1102', '', 'Szőlőbor termelése');
INSERT INTO sic (code, sictype,description) VALUES ('1103', '', 'Gyümölcsbor termelése');
INSERT INTO sic (code, sictype,description) VALUES ('1104', '', 'Egyéb nem desztillált, erjesztett ital gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1105', '', 'Sörgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('1106', '', 'Malátagyártás');
INSERT INTO sic (code, sictype,description) VALUES ('1107', '', 'Üdítőital, ásványvíz gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('12', 'H', 'Dohánytermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('120', 'H', 'Dohánytermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1200', '', 'Dohánytermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('13', 'H', 'Textília gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('131', 'H', 'Textilszálak fonása');
INSERT INTO sic (code, sictype,description) VALUES ('1310', '', 'Textilszálak fonása');
INSERT INTO sic (code, sictype,description) VALUES ('132', 'H', 'Textilszövés');
INSERT INTO sic (code, sictype,description) VALUES ('1320', '', 'Textilszövés');
INSERT INTO sic (code, sictype,description) VALUES ('133', 'H', 'Textilkikészítés');
INSERT INTO sic (code, sictype,description) VALUES ('1330', '', 'Textilkikészítés');
INSERT INTO sic (code, sictype,description) VALUES ('139', 'H', 'Egyéb textiláru gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1391', '', 'Kötött, hurkolt kelme gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1393', '', 'Szőnyeggyártás');
INSERT INTO sic (code, sictype,description) VALUES ('1394', '', 'Kötéláru gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1396', '', 'Műszaki textiláru gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1399', '', 'Egyéb textiláru gyártása mns');
INSERT INTO sic (code, sictype,description) VALUES ('14', 'H', 'Ruházati termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1411', '', 'Bőrruházat gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1412', '', 'Munkaruházat gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1414', '', 'Alsóruházat gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1419', '', 'Egyéb ruházat, kiegészítők gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('142', 'H', 'Szőrmecikk gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1420', '', 'Szőrmecikk gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('143', 'H', 'Kötött, hurkolt cikk gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1431', '', 'Kötött, hurkolt harisnyafélék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1439', '', 'Egyéb kötött, hurkolt ruházati termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('15', 'H', 'Bőr, bőrtermék, lábbeli gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('151', 'H', 'Bőr, szőrme kikészítése; táskafélék, szíjazat gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1511', '', 'Bőr, szőrme kikészítése');
INSERT INTO sic (code, sictype,description) VALUES ('1512', '', 'Táskafélék, szíjazat gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('152', 'H', 'Lábbeligyártás');
INSERT INTO sic (code, sictype,description) VALUES ('1520', '', 'Lábbeligyártás');
INSERT INTO sic (code, sictype,description) VALUES ('161', 'H', 'Fűrészárugyártás');
INSERT INTO sic (code, sictype,description) VALUES ('1610', '', 'Fűrészárugyártás');
INSERT INTO sic (code, sictype,description) VALUES ('162', 'H', 'Fa-, parafatermék, fonottáru gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1621', '', 'Falemezgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('1622', '', 'Parkettagyártás');
INSERT INTO sic (code, sictype,description) VALUES ('1623', '', 'Épületasztalos-ipari termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1624', '', 'Tároló fatermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1629', '', 'Egyéb fa-, parafatermék, fonottáru gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('17', 'H', 'Papír, papírtermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('171', 'H', 'Papíripari rostanyag, papír gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1711', '', 'Papíripari rostanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1712', '', 'Papírgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('172', 'H', 'Papírtermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1721', '', 'Papír csomagolóeszköz gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1722', '', 'Háztartási, egészségügyi papírtermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1723', '', 'Irodai papíráru gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('1724', '', 'Tapétagyártás');
INSERT INTO sic (code, sictype,description) VALUES ('1729', '', 'Egyéb papír-, kartontermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('18', 'H', 'Nyomdai és egyéb sokszorosítási tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('181', 'H', 'Nyomdai tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('1811', '', 'Napilapnyomás');
INSERT INTO sic (code, sictype,description) VALUES ('1813', '', 'Nyomdai előkészítő tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('1814', '', 'Könyvkötés, kapcsolódó szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('182', 'H', 'Egyéb sokszorosítás');
INSERT INTO sic (code, sictype,description) VALUES ('1820', '', 'Egyéb sokszorosítás');
INSERT INTO sic (code, sictype,description) VALUES ('19', 'H', 'Kokszgyártás, kőolaj-feldolgozás');
INSERT INTO sic (code, sictype,description) VALUES ('191', 'H', 'Kokszgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('1910', '', 'Kokszgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('192', 'H', 'Kőolaj-feldolgozás');
INSERT INTO sic (code, sictype,description) VALUES ('1920', '', 'Kőolaj-feldolgozás');
INSERT INTO sic (code, sictype,description) VALUES ('20', 'H', 'Vegyi anyag, termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('201', 'H', 'Vegyi alapanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2011', '', 'Ipari gáz gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2012', '', 'Színezék, pigment gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2013', '', 'Szervetlen vegyi alapanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2014', '', 'Szerves vegyi alapanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2015', '', 'Műtrágya, nitrogénvegyület gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2016', '', 'Műanyag-alapanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2017', '', 'Szintetikus kaucsuk alapanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('202', 'H', 'Mezőgazdasági vegyi termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2020', '', 'Mezőgazdasági vegyi termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('203', 'H', 'Festék, bevonóanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2030', '', 'Festék, bevonóanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('204', 'H', 'Tisztítószer, testápolási cikk gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2041', '', 'Tisztítószer gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2042', '', 'Testápolási cikk gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('205', 'H', 'Egyéb vegyi termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2051', '', 'Robbanóanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2052', '', 'Ragasztószergyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2053', '', 'Illóolajgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2059', '', 'Mns egyéb vegyi termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('206', 'H', 'Vegyi szál gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2060', '', 'Vegyi szál gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('21', 'H', 'Gyógyszergyártás');
INSERT INTO sic (code, sictype,description) VALUES ('211', 'H', 'Gyógyszeralapanyag-gyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2110', '', 'Gyógyszeralapanyag-gyártás');
INSERT INTO sic (code, sictype,description) VALUES ('212', 'H', 'Gyógyszerkészítmény gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2120', '', 'Gyógyszerkészítmény gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('22', 'H', 'Gumi-, műanyag termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('221', 'H', 'Gumitermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2211', '', 'Gumiabroncs, gumitömlő gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2219', '', 'Egyéb gumitermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('222', 'H', 'Műanyag termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2221', '', 'Műanyag lap, lemez, fólia, cső, profil gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2222', '', 'Műanyag csomagolóeszköz gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2223', '', 'Műanyag építőanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2229', '', 'Egyéb műanyag termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('23', 'H', 'Nemfém ásványi termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('231', 'H', 'Üveg, üvegtermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2311', '', 'Síküveggyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2312', '', 'Síküveg továbbfeldolgozása');
INSERT INTO sic (code, sictype,description) VALUES ('2313', '', 'Öblösüveggyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2314', '', 'Üvegszálgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2319', '', 'Műszaki, egyéb üvegtermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('232', 'H', 'Tűzálló termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2320', '', 'Tűzálló termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('233', 'H', 'Kerámia, agyag építőanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2331', '', 'Kerámiacsempe, -lap gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2332', '', 'Égetett agyag építőanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('234', 'H', 'Porcelán, kerámiatermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2341', '', 'Háztartási kerámia gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2342', '', 'Egészségügyi kerámia gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2343', '', 'Kerámia szigetelő gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2344', '', 'Műszaki kerámia gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2349', '', 'Egyéb kerámiatermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('235', 'H', 'Cement-, mész-, gipszgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2351', '', 'Cementgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2352', '', 'Mész-, gipszgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('236', 'H', 'Beton-, gipsz-, cementtermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2361', '', 'Építési betontermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2362', '', 'Építési gipsztermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2363', '', 'Előre kevert beton gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2364', '', 'Habarcsgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2365', '', 'Szálerősítésű cement gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2369', '', 'Egyéb beton-, gipsz-, cementtermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('237', 'H', 'Kőmegmunkálás');
INSERT INTO sic (code, sictype,description) VALUES ('2370', '', 'Kőmegmunkálás');
INSERT INTO sic (code, sictype,description) VALUES ('239', 'H', 'Egyéb csiszolótermék és nemfém ásványi termék gyártása mns');
INSERT INTO sic (code, sictype,description) VALUES ('2391', '', 'Csiszolótermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2399', '', 'Mns egyéb nemfém ásványi termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('24', 'H', 'Fémalapanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('241', 'H', 'Vas-, acél-, vasötvözet-alapanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2410', '', 'Vas-, acél-, vasötvözet-alapanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('242', 'H', 'Acélcsőgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2420', '', 'Acélcsőgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('243', 'H', 'Egyéb kohászati termék gyártása acélból');
INSERT INTO sic (code, sictype,description) VALUES ('2431', '', 'Hidegen húzott acélrúd gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2432', '', 'Hidegen hengerelt keskeny acélszalag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2433', '', 'Hidegen hajlított acélidom gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2434', '', 'Hidegen húzott acélhuzal gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('244', 'H', 'Nem vas fém alapanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2441', '', 'Nemesfémgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2442', '', 'Alumíniumgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2443', '', 'Ólom, cink, ón gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2444', '', 'Rézgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2445', '', 'Egyéb nem vas fém gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2446', '', 'Nukleáris fűtőanyag gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('245', 'H', 'Fémöntés');
INSERT INTO sic (code, sictype,description) VALUES ('2451', '', 'Vasöntés');
INSERT INTO sic (code, sictype,description) VALUES ('2452', '', 'Acélöntés');
INSERT INTO sic (code, sictype,description) VALUES ('2453', '', 'Könnyűfémöntés');
INSERT INTO sic (code, sictype,description) VALUES ('2454', '', 'Egyéb nem vas fém öntése');
INSERT INTO sic (code, sictype,description) VALUES ('25', 'H', 'Fémfeldolgozási termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('251', 'H', 'Fémszerkezet, -épületelem gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2511', '', 'Fémszerkezet gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2512', '', 'Fém épületelem gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('252', 'H', 'Fűtési kazán, radiátor, fémtartály gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2521', '', 'Központi fűtési kazán, radiátor gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2529', '', 'Fémtartály gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('253', 'H', 'Gőzkazán gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2530', '', 'Gőzkazán gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('254', 'H', 'Fegyver-, lőszergyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2540', '', 'Fegyver-, lőszergyártás');
INSERT INTO sic (code, sictype,description) VALUES ('255', 'H', 'Fémalakítás, porkohászat');
INSERT INTO sic (code, sictype,description) VALUES ('2550', '', 'Fémalakítás, porkohászat');
INSERT INTO sic (code, sictype,description) VALUES ('256', 'H', 'Fém felületkezelése, megmunkálása');
INSERT INTO sic (code, sictype,description) VALUES ('2561', '', 'Fémfelület-kezelés');
INSERT INTO sic (code, sictype,description) VALUES ('2562', '', 'Fémmegmunkálás');
INSERT INTO sic (code, sictype,description) VALUES ('257', 'H', 'Evőeszköz, szerszám, általános fémáru gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2571', '', 'Evőeszköz gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2572', '', 'Lakat-, zárgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2573', '', 'Szerszámgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('259', 'H', 'Egyéb fémfeldolgozási termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2591', '', 'Acél tárolóeszköz gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2592', '', 'Könnyűfém csomagolóeszköz gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2593', '', 'Huzaltermék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2594', '', 'Kötőelem, csavar gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2599', '', 'Mns egyéb fémfeldolgozási termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('26', 'H', 'Számítógép, elektronikai, optikai termék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('261', 'H', 'Elektronikai alkatrész, áramköri kártya gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2611', '', 'Elektronikai alkatrész gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2612', '', 'Elektronikai áramköri kártya gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('262', 'H', 'Számítógép, perifériás egység gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2620', '', 'Számítógép, perifériás egység gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('263', 'H', 'Híradás-technikai berendezés gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2630', '', 'Híradás-technikai berendezés gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('264', 'H', 'Elektronikus fogyasztási cikk gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2640', '', 'Elektronikus fogyasztási cikk gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('265', 'H', 'Műszer-, óragyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2651', '', 'Mérőműszergyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2652', '', 'Óragyártás');
INSERT INTO sic (code, sictype,description) VALUES ('266', 'H', 'Elektronikus orvosi berendezés gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2660', '', 'Elektronikus orvosi berendezés gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('267', 'H', 'Optikai eszköz gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2670', '', 'Optikai eszköz gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('268', 'H', 'Mágneses, optikai információhordozó gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2680', '', 'Mágneses, optikai információhordozó gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('27', 'H', 'Villamos berendezés gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('271', 'H', 'Villamos motor, áramfejlesztő, áramelosztó, -szabályozó készülék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2711', '', 'Villamos motor, áramfejlesztő gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2712', '', 'Áramelosztó, -szabályozó készülék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('272', 'H', 'Akkumulátor, szárazelem gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2720', '', 'Akkumulátor, szárazelem gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('273', 'H', 'Vezeték, kábel, szerelvény gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2731', '', 'Száloptikai kábel gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2732', '', 'Egyéb elektronikus, villamos vezeték, kábel gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2733', '', 'Szerelvény gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('274', 'H', 'Villamos világítóeszköz gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2740', '', 'Villamos világítóeszköz gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('275', 'H', 'Háztartási készülék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2751', '', 'Háztartási villamos készülék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2752', '', 'Nem villamos háztartási készülék gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('279', 'H', 'Egyéb villamos berendezés gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2790', '', 'Egyéb villamos berendezés gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('28', 'H', 'Gép, gépi berendezés gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('281', 'H', 'Általános rendeltetésű gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2812', '', 'Hidraulikus, pneumatikus berendezés gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2813', '', 'Egyéb szivattyú, kompresszor gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2814', '', 'Csap, szelep gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2815', '', 'Csapágy, erőátviteli elem gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('282', 'H', 'Egyéb általános rendeltetésű gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2821', '', 'Fűtőberendezés, kemence gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2822', '', 'Emelő-, anyagmozgató gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2824', '', 'Gépi meghajtású hordozható kézi szerszámgép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2825', '', 'Nem háztartási hűtő, légállapot-szabályozó gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2829', '', 'Mns egyéb általános rendeltetésű gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('283', 'H', 'Mezőgazdasági, erdészeti gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2830', '', 'Mezőgazdasági, erdészeti gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('284', 'H', 'Szerszámgépgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('2841', '', 'Fémmegmunkáló szerszámgép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2849', '', 'Egyéb szerszámgép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('289', 'H', 'Egyéb speciális rendeltetésű gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2891', '', 'Kohászati gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2892', '', 'Bányászati, építőipari gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2893', '', 'Élelmiszer-, dohányipari gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2894', '', 'Textil-, ruházati, bőripari gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2895', '', 'Papíripari gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2896', '', 'Műanyag-, gumifeldolgozó gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2899', '', 'Mns egyéb speciális gép gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('29', 'H', 'Közúti jármű gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('291', 'H', 'Közúti gépjármű gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2910', '', 'Közúti gépjármű gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('292', 'H', 'Gépjármű-karosszéria, pótkocsi gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2920', '', 'Gépjármű-karosszéria, pótkocsi gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('293', 'H', 'Közúti jármű alkatrészeinek gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2931', '', 'Járművillamossági, -elektronikai készülékek gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('2932', '', 'Közúti jármű, járműmotor alkatrészeinek gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('30', 'H', 'Egyéb jármű gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('301', 'H', 'Hajó, csónak gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('3011', '', 'Hajógyártás');
INSERT INTO sic (code, sictype,description) VALUES ('3012', '', 'Szabadidő-, sporthajó gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('302', 'H', 'Vasúti, kötöttpályás jármű gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('3020', '', 'Vasúti, kötöttpályás jármű gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('303', 'H', 'Légi, űrjármű gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('3030', '', 'Légi, űrjármű gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('304', 'H', 'Katonai harcjármű gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('3040', '', 'Katonai harcjármű gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('309', 'H', 'Egyéb jármű gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('3091', '', 'Motorkerékpár gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('3092', '', 'Kerékpár, mozgássérültkocsi gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('3099', '', 'Mns egyéb jármű gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('31', 'H', 'Bútorgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('310', 'H', 'Bútorgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('3101', '', 'Irodabútor gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('3102', '', 'Konyhabútorgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('3103', '', 'Ágybetét gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('3109', '', 'Egyéb bútor gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('32', 'H', 'Egyéb feldolgozóipari tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('321', 'H', 'Ékszergyártás');
INSERT INTO sic (code, sictype,description) VALUES ('3211', '', 'Érmegyártás');
INSERT INTO sic (code, sictype,description) VALUES ('3212', '', 'Ékszergyártás');
INSERT INTO sic (code, sictype,description) VALUES ('3213', '', 'Divatékszer gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('322', 'H', 'Hangszergyártás');
INSERT INTO sic (code, sictype,description) VALUES ('3220', '', 'Hangszergyártás');
INSERT INTO sic (code, sictype,description) VALUES ('323', 'H', 'Sportszergyártás');
INSERT INTO sic (code, sictype,description) VALUES ('3230', '', 'Sportszergyártás');
INSERT INTO sic (code, sictype,description) VALUES ('324', 'H', 'Játékgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('3240', '', 'Játékgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('325', 'H', 'Orvosi eszköz gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('3250', '', 'Orvosi eszköz gyártása');
INSERT INTO sic (code, sictype,description) VALUES ('329', 'H', 'Mns egyéb feldolgozóipari tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('3291', '', 'Seprű-, kefegyártás');
INSERT INTO sic (code, sictype,description) VALUES ('3299', '', 'Egyéb mns feldolgozóipari tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('33', 'H', 'Ipari gép, berendezés, eszköz javítása');
INSERT INTO sic (code, sictype,description) VALUES ('331', 'H', 'Ipari gép, berendezés, eszköz javítása');
INSERT INTO sic (code, sictype,description) VALUES ('3311', '', 'Fémfeldolgozási termék javítása');
INSERT INTO sic (code, sictype,description) VALUES ('3312', '', 'Ipari gép, berendezés javítása');
INSERT INTO sic (code, sictype,description) VALUES ('3313', '', 'Elektronikus, optikai eszköz javítása');
INSERT INTO sic (code, sictype,description) VALUES ('3314', '', 'Ipari villamos gép, berendezés javítása');
INSERT INTO sic (code, sictype,description) VALUES ('3315', '', 'Hajó, csónak javítása');
INSERT INTO sic (code, sictype,description) VALUES ('3316', '', 'Repülőgép, űrhajó javítása');
INSERT INTO sic (code, sictype,description) VALUES ('3317', '', 'Egyéb közlekedési eszköz javítása');
INSERT INTO sic (code, sictype,description) VALUES ('3319', '', 'Egyéb ipari eszköz javítása');
INSERT INTO sic (code, sictype,description) VALUES ('332', 'H', 'Ipari gép, berendezés üzembe helyezése');
INSERT INTO sic (code, sictype,description) VALUES ('3320', '', 'Ipari gép, berendezés üzembe helyezése');
INSERT INTO sic (code, sictype,description) VALUES ('35', 'H', 'Villamosenergia-, gáz-, gőzellátás, légkondicionálás');
INSERT INTO sic (code, sictype,description) VALUES ('351', 'H', 'Villamosenergia-termelés, -ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('3511', '', 'Villamosenergia-termelés');
INSERT INTO sic (code, sictype,description) VALUES ('3512', '', 'Villamosenergia-szállítás');
INSERT INTO sic (code, sictype,description) VALUES ('3513', '', 'Villamosenergia-elosztás');
INSERT INTO sic (code, sictype,description) VALUES ('3514', '', 'Villamosenergia-kereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('352', 'H', 'Gázellátás');
INSERT INTO sic (code, sictype,description) VALUES ('3521', '', 'Gázgyártás');
INSERT INTO sic (code, sictype,description) VALUES ('3522', '', 'Gázelosztás');
INSERT INTO sic (code, sictype,description) VALUES ('3523', '', 'Gázkereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('353', 'H', 'Gőzellátás, légkondicionálás');
INSERT INTO sic (code, sictype,description) VALUES ('3530', '', 'Gőzellátás, légkondicionálás');
INSERT INTO sic (code, sictype,description) VALUES ('36', 'H', 'Víztermelés, -kezelés, -ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('360', 'H', 'Víztermelés, -kezelés, -ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('3600', '', 'Víztermelés, -kezelés, -ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('37', 'H', 'Szennyvíz gyűjtése, kezelése');
INSERT INTO sic (code, sictype,description) VALUES ('370', 'H', 'Szennyvíz gyűjtése, kezelése');
INSERT INTO sic (code, sictype,description) VALUES ('3700', '', 'Szennyvíz gyűjtése, kezelése');
INSERT INTO sic (code, sictype,description) VALUES ('38', 'H', 'Hulladékgazdálkodás');
INSERT INTO sic (code, sictype,description) VALUES ('381', 'H', 'Hulladékgyűjtés');
INSERT INTO sic (code, sictype,description) VALUES ('3811', '', 'Nem veszélyes hulladék gyűjtése');
INSERT INTO sic (code, sictype,description) VALUES ('3812', '', 'Veszélyes hulladék gyűjtése');
INSERT INTO sic (code, sictype,description) VALUES ('382', 'H', 'Hulladékkezelés, -ártalmatlanítás');
INSERT INTO sic (code, sictype,description) VALUES ('3821', '', 'Nem veszélyes hulladék kezelése, ártalmatlanítása');
INSERT INTO sic (code, sictype,description) VALUES ('3822', '', 'Veszélyes hulladék kezelése, ártalmatlanítása');
INSERT INTO sic (code, sictype,description) VALUES ('383', 'H', 'Hulladékanyag hasznosítása');
INSERT INTO sic (code, sictype,description) VALUES ('3831', '', 'Használt eszköz bontása');
INSERT INTO sic (code, sictype,description) VALUES ('3832', '', 'Hulladék újrahasznosítása');
INSERT INTO sic (code, sictype,description) VALUES ('39', 'H', 'Szennyeződésmentesítés, egyéb hulladékkezelés');
INSERT INTO sic (code, sictype,description) VALUES ('390', 'H', 'Szennyeződésmentesítés, egyéb hulladékkezelés');
INSERT INTO sic (code, sictype,description) VALUES ('3900', '', 'Szennyeződésmentesítés, egyéb hulladékkezelés');
INSERT INTO sic (code, sictype,description) VALUES ('41', 'H', 'Épületek építése');
INSERT INTO sic (code, sictype,description) VALUES ('411', 'H', 'Épületépítési projekt szervezése');
INSERT INTO sic (code, sictype,description) VALUES ('4110', '', 'Épületépítési projekt szervezése');
INSERT INTO sic (code, sictype,description) VALUES ('412', 'H', 'Lakó- és nem lakó épület építése');
INSERT INTO sic (code, sictype,description) VALUES ('4120', '', 'Lakó- és nem lakó épület építése');
INSERT INTO sic (code, sictype,description) VALUES ('42', 'H', 'Egyéb építmény építése');
INSERT INTO sic (code, sictype,description) VALUES ('421', 'H', 'Út, vasút építése');
INSERT INTO sic (code, sictype,description) VALUES ('4211', '', 'Út, autópálya építése');
INSERT INTO sic (code, sictype,description) VALUES ('4212', '', 'Vasút építése');
INSERT INTO sic (code, sictype,description) VALUES ('4213', '', 'Híd, alagút építése');
INSERT INTO sic (code, sictype,description) VALUES ('422', 'H', 'Közműépítés');
INSERT INTO sic (code, sictype,description) VALUES ('4221', '', 'Folyadék szállítására szolgáló közmű építése');
INSERT INTO sic (code, sictype,description) VALUES ('4222', '', 'Elektromos, híradás-technikai célú közmű építése');
INSERT INTO sic (code, sictype,description) VALUES ('429', 'H', 'Mns egyéb építmény építése');
INSERT INTO sic (code, sictype,description) VALUES ('4291', '', 'Vízi létesítmény építése');
INSERT INTO sic (code, sictype,description) VALUES ('4299', '', 'Egyéb mns építés');
INSERT INTO sic (code, sictype,description) VALUES ('43', 'H', 'Speciális szaképítés');
INSERT INTO sic (code, sictype,description) VALUES ('431', 'H', 'Bontás, építési terület előkészítése');
INSERT INTO sic (code, sictype,description) VALUES ('4311', '', 'Bontás');
INSERT INTO sic (code, sictype,description) VALUES ('4312', '', 'Építési terület előkészítése');
INSERT INTO sic (code, sictype,description) VALUES ('4313', '', 'Talajmintavétel, próbafúrás');
INSERT INTO sic (code, sictype,description) VALUES ('432', 'H', 'Épületgépészeti szerelés');
INSERT INTO sic (code, sictype,description) VALUES ('4321', '', 'Villanyszerelés');
INSERT INTO sic (code, sictype,description) VALUES ('4322', '', 'Víz-, gáz-, fűtés-, légkondicionáló-szerelés');
INSERT INTO sic (code, sictype,description) VALUES ('4329', '', 'Egyéb épületgépészeti szerelés');
INSERT INTO sic (code, sictype,description) VALUES ('433', 'H', 'Befejező építés');
INSERT INTO sic (code, sictype,description) VALUES ('4331', '', 'Vakolás');
INSERT INTO sic (code, sictype,description) VALUES ('4332', '', 'Épületasztalos-szerkezet szerelése');
INSERT INTO sic (code, sictype,description) VALUES ('4333', '', 'Padló-, falburkolás');
INSERT INTO sic (code, sictype,description) VALUES ('4334', '', 'Festés, üvegezés');
INSERT INTO sic (code, sictype,description) VALUES ('4339', '', 'Egyéb befejező építés mns');
INSERT INTO sic (code, sictype,description) VALUES ('439', 'H', 'Egyéb speciális szaképítés');
INSERT INTO sic (code, sictype,description) VALUES ('4391', '', 'Tetőfedés, tetőszerkezet-építés');
INSERT INTO sic (code, sictype,description) VALUES ('4399', '', 'Egyéb speciális szaképítés mns');
INSERT INTO sic (code, sictype,description) VALUES ('45', 'H', 'Gépjármű, motorkerékpár kereskedelme, javítása');
INSERT INTO sic (code, sictype,description) VALUES ('451', 'H', 'Gépjármű-kereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4511', '', 'Személygépjármű-, könnyűgépjármű-kereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4519', '', 'Egyéb gépjármű-kereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('452', 'H', 'Gépjárműjavítás, -karbantartás');
INSERT INTO sic (code, sictype,description) VALUES ('4520', '', 'Gépjárműjavítás, -karbantartás');
INSERT INTO sic (code, sictype,description) VALUES ('453', 'H', 'Gépjárműalkatrész-kereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4531', '', 'Gépjárműalkatrész-nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4532', '', 'Gépjárműalkatrész-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('454', 'H', 'Motorkerékpár, -alkatrész kereskedelme, javítása');
INSERT INTO sic (code, sictype,description) VALUES ('4540', '', 'Motorkerékpár, -alkatrész kereskedelme, javítása');
INSERT INTO sic (code, sictype,description) VALUES ('461', 'H', 'Ügynöki nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4611', '', 'Mezőgazdasági termék ügynöki nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4612', '', 'Alapanyag, üzemanyag ügynöki nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4613', '', 'Fa-, építési anyag ügynöki nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4614', '', 'Gép, hajó, repülőgép ügynöki nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4615', '', 'Bútor, háztartási áru, fémáru ügynöki nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4616', '', 'Textil, ruházat, lábbeli, bőráru ügynöki nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4617', '', 'Élelmiszer, ital, dohányáru ügynöki nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4618', '', 'Egyéb termék ügynöki nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4619', '', 'Vegyes termékkörű ügynöki nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('462', 'H', 'Mezőgazdasági nyersanyag, élőállat nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4621', '', 'Gabona, dohány, vetőmag, takarmány nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4622', '', 'Dísznövény nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4623', '', 'Élőállat nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4624', '', 'Bőr nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('463', 'H', 'Élelmiszer, ital, dohányáru nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4631', '', 'Zöldség-, gyümölcs-nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4632', '', 'Hús-, húskészítmény nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4633', '', 'Tejtermék, tojás, zsiradék nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4634', '', 'Ital nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4635', '', 'Dohányáru nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4636', '', 'Cukor, édesség nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4637', '', 'Kávé-, tea-, kakaó-, fűszer-nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4638', '', 'Egyéb élelmiszer nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4639', '', 'Élelmiszer, ital, dohányáru vegyes nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('464', 'H', 'Háztartási cikk nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4641', '', 'Textil-nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4642', '', 'Ruházat, lábbeli nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4643', '', 'Elektronikus háztartási cikk nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4644', '', 'Porcelán-, üvegáru-, tisztítószer-nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4645', '', 'Illatszer nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4646', '', 'Gyógyszer, gyógyászati termék nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4647', '', 'Bútor, szőnyeg, világítóberendezés nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4648', '', 'Óra-, ékszer-nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4649', '', 'Egyéb háztartási cikk nagykereskedelme mns');
INSERT INTO sic (code, sictype,description) VALUES ('465', 'H', 'Információtechnológiai, híradás-technikai termék nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4651', '', 'Számítógép, periféria, szoftver nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4652', '', 'Elektronikus, híradás-technikai berendezés és alkatrészei nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('466', 'H', 'Egyéb gép, berendezés, tartozék nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4661', '', 'Mezőgazdasági gép, berendezés nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4662', '', 'Szerszámgép-nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4663', '', 'Bányászati-, építőipari gép nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4664', '', 'Textilipari gép, varró-, kötőgép nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4665', '', 'Irodabútor-nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4666', '', 'Egyéb irodagép, -berendezés nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4669', '', 'Egyéb mns gép, berendezés nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('467', 'H', 'Egyéb szakosodott nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4671', '', 'Üzem-, tüzelőanyag nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4672', '', 'Fém-, érc-nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4673', '', 'Fa-, építőanyag-, szaniteráru-nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4674', '', 'Fémáru, szerelvény, fűtési berendezés nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4675', '', 'Vegyi áru nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4676', '', 'Egyéb termelési célú termék nagykereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4677', '', 'Hulladék-nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('469', 'H', 'Vegyestermékkörű nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4690', '', 'Vegyestermékkörű nagykereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('471', 'H', 'Nem szakosodott bolti vegyes kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4711', '', 'Élelmiszer jellegű bolti vegyes kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4719', '', 'Iparcikk jellegű bolti vegyes kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('472', 'H', 'Élelmiszer, ital, dohányáru kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4721', '', 'Zöldség, gyümölcs kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4722', '', 'Hús-, húsáru kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4723', '', 'Hal kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4724', '', 'Kenyér-, pékáru-, édesség-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4725', '', 'Ital-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4726', '', 'Dohányáru-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4729', '', 'Egyéb élelmiszer-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('473', 'H', 'Gépjárműüzemanyag-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4730', '', 'Gépjárműüzemanyag-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('474', 'H', 'Információs, híradás-technikai termék kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4741', '', 'Számítógép, periféria, szoftver kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4742', '', 'Telekommunikációs termék kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4743', '', 'Audio-, videoberendezés kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('475', 'H', 'Egyéb háztartási cikk kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4751', '', 'Textil-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4752', '', 'Vasáru-, festék-, üveg-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4753', '', 'Takaró, szőnyeg, fal-, padlóburkoló kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4754', '', 'Villamos háztartási készülék kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4759', '', 'Bútor, világítási eszköz, egyéb háztartási cikk kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('476', 'H', 'Kulturális, szabadidős cikk bolti kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4761', '', 'Könyv-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4762', '', 'Újság-, papíráru-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4763', '', 'Zene-, videofelvétel kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4764', '', 'Sportszer-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4765', '', 'Játék-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('477', 'H', 'Egyéb mns áru kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4771', '', 'Ruházat kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4772', '', 'Lábbeli-, bőráru-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4773', '', 'Gyógyszer-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4774', '', 'Gyógyászati termék kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4775', '', 'Illatszer-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4776', '', 'Dísznövény, vetőmag, műtrágya, hobbiállat-eledel kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4777', '', 'Óra-, ékszer-kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4778', '', 'Egyéb mns új áru kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4779', '', 'Használtcikk bolti kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('478', 'H', 'Piaci kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4781', '', 'Élelmiszer, ital, dohányáru piaci kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4782', '', 'Textil, ruházat, lábbeli piaci kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('4789', '', 'Egyéb áruk piaci kiskereskedelme');
INSERT INTO sic (code, sictype,description) VALUES ('479', 'H', 'Nem bolti, piaci kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4791', '', 'Csomagküldő, internetes kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('4799', '', 'Egyéb nem bolti, piaci kiskereskedelem');
INSERT INTO sic (code, sictype,description) VALUES ('49', 'H', 'Szárazföldi, csővezetékes szállítás');
INSERT INTO sic (code, sictype,description) VALUES ('491', 'H', 'Helyközi vasúti személyszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('4910', '', 'Helyközi vasúti személyszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('492', 'H', 'Vasúti áruszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('4920', '', 'Vasúti áruszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('493', 'H', 'Egyéb szárazföldi személyszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('4931', '', 'Városi, elővárosi szárazföldi személyszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('4932', '', 'Taxis személyszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('4939', '', 'Mns egyéb szárazföldi személyszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('494', 'H', 'Közúti áruszállítás, költöztetés');
INSERT INTO sic (code, sictype,description) VALUES ('4941', '', 'Közúti áruszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('4942', '', 'Költöztetés');
INSERT INTO sic (code, sictype,description) VALUES ('495', 'H', 'Csővezetékes szállítás');
INSERT INTO sic (code, sictype,description) VALUES ('4950', '', 'Csővezetékes szállítás');
INSERT INTO sic (code, sictype,description) VALUES ('50', 'H', 'Vízi szállítás');
INSERT INTO sic (code, sictype,description) VALUES ('501', 'H', 'Tengeri személyszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('5010', '', 'Tengeri személyszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('502', 'H', 'Tengeri áruszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('5020', '', 'Tengeri áruszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('503', 'H', 'Belvízi személyszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('5030', '', 'Belvízi személyszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('504', 'H', 'Belvízi áruszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('5040', '', 'Belvízi áruszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('51', 'H', 'Légi szállítás');
INSERT INTO sic (code, sictype,description) VALUES ('511', 'H', 'Légi személyszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('5110', '', 'Légi személyszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('512', 'H', 'Légi áruszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('5121', '', 'Légi áruszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('5122', '', 'Űrszállítás');
INSERT INTO sic (code, sictype,description) VALUES ('52', 'H', 'Raktározás, szállítást kiegészítő tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('521', 'H', 'Raktározás, tárolás');
INSERT INTO sic (code, sictype,description) VALUES ('5210', '', 'Raktározás, tárolás');
INSERT INTO sic (code, sictype,description) VALUES ('522', 'H', 'Szállítást kiegészítő tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('5221', '', 'Szárazföldi szállítást kiegészítő szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('5222', '', 'Vízi szállítást kiegészítő szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('5223', '', 'Légi szállítást kiegészítő szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('5224', '', 'Rakománykezelés');
INSERT INTO sic (code, sictype,description) VALUES ('5229', '', 'Egyéb szállítást kiegészítő szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('53', 'H', 'Postai, futárpostai tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('532', 'H', 'Egyéb postai, futárpostai tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('5320', '', 'Egyéb postai, futárpostai tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('55', 'H', 'Szálláshely-szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('551', 'H', 'Szállodai szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('5510', '', 'Szállodai szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('552', 'H', 'Üdülési, egyéb átmeneti szálláshely-szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('5520', '', 'Üdülési, egyéb átmeneti szálláshely-szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('553', 'H', 'Kempingszolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('5530', '', 'Kempingszolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('559', 'H', 'Egyéb szálláshely-szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('5590', '', 'Egyéb szálláshely-szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('56', 'H', 'Vendéglátás');
INSERT INTO sic (code, sictype,description) VALUES ('561', 'H', 'Éttermi, mozgó vendéglátás');
INSERT INTO sic (code, sictype,description) VALUES ('5610', '', 'Éttermi, mozgó vendéglátás');
INSERT INTO sic (code, sictype,description) VALUES ('562', 'H', 'Rendezvényi étkeztetés és egyéb vendéglátás');
INSERT INTO sic (code, sictype,description) VALUES ('5621', '', 'Rendezvényi étkeztetés');
INSERT INTO sic (code, sictype,description) VALUES ('5629', '', 'Egyéb vendéglátás');
INSERT INTO sic (code, sictype,description) VALUES ('563', 'H', 'Italszolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('5630', '', 'Italszolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('58', 'H', 'Kiadói tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('581', 'H', 'Kiadói tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('5811', '', 'Könyvkiadás');
INSERT INTO sic (code, sictype,description) VALUES ('5812', '', 'Címtárak, levelezőjegyzékek kiadása');
INSERT INTO sic (code, sictype,description) VALUES ('5813', '', 'Napilapkiadás');
INSERT INTO sic (code, sictype,description) VALUES ('5814', '', 'Folyóirat, időszaki kiadvány kiadása');
INSERT INTO sic (code, sictype,description) VALUES ('5819', '', 'Egyéb kiadói tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('582', 'H', 'Szoftverkiadás');
INSERT INTO sic (code, sictype,description) VALUES ('5821', '', 'Számítógépes játék kiadása');
INSERT INTO sic (code, sictype,description) VALUES ('5829', '', 'Egyéb szoftverkiadás');
INSERT INTO sic (code, sictype,description) VALUES ('59', 'H', 'Film, video, televízióműsor gyártása, hangfelvétel-kiadás');
INSERT INTO sic (code, sictype,description) VALUES ('591', 'H', 'Film-, video-, televízióműsor-gyártás');
INSERT INTO sic (code, sictype,description) VALUES ('5911', '', 'Film-, video-, televízióműsor-gyártás');
INSERT INTO sic (code, sictype,description) VALUES ('5912', '', 'Film-, videogyártás, televíziós műsorfelvétel utómunkálatai');
INSERT INTO sic (code, sictype,description) VALUES ('5913', '', 'Film-, video- és televízióprogram terjesztése');
INSERT INTO sic (code, sictype,description) VALUES ('5914', '', 'Filmvetítés');
INSERT INTO sic (code, sictype,description) VALUES ('592', 'H', 'Hangfelvétel készítése, kiadása');
INSERT INTO sic (code, sictype,description) VALUES ('5920', '', 'Hangfelvétel készítése, kiadása');
INSERT INTO sic (code, sictype,description) VALUES ('60', 'H', 'Műsorösszeállítás, műsorszolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('601', 'H', 'Rádióműsor-szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('6010', '', 'Rádióműsor-szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('602', 'H', 'Televízióműsor összeállítása, szolgáltatása');
INSERT INTO sic (code, sictype,description) VALUES ('6020', '', 'Televízióműsor összeállítása, szolgáltatása');
INSERT INTO sic (code, sictype,description) VALUES ('61', 'H', 'Távközlés');
INSERT INTO sic (code, sictype,description) VALUES ('611', 'H', 'Vezetékes távközlés');
INSERT INTO sic (code, sictype,description) VALUES ('6110', '', 'Vezetékes távközlés');
INSERT INTO sic (code, sictype,description) VALUES ('612', 'H', 'Vezeték nélküli távközlés');
INSERT INTO sic (code, sictype,description) VALUES ('6120', '', 'Vezeték nélküli távközlés');
INSERT INTO sic (code, sictype,description) VALUES ('613', 'H', 'Műholdas távközlés');
INSERT INTO sic (code, sictype,description) VALUES ('6130', '', 'Műholdas távközlés');
INSERT INTO sic (code, sictype,description) VALUES ('619', 'H', 'Egyéb távközlés');
INSERT INTO sic (code, sictype,description) VALUES ('6190', '', 'Egyéb távközlés');
INSERT INTO sic (code, sictype,description) VALUES ('62', 'H', 'Információ-technológiai szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('620', 'H', 'Információ-technológiai szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('6201', '', 'Számítógépes programozás');
INSERT INTO sic (code, sictype,description) VALUES ('6202', '', 'Információ-technológiai szaktanácsadás');
INSERT INTO sic (code, sictype,description) VALUES ('6203', '', 'Számítógép-üzemeltetés');
INSERT INTO sic (code, sictype,description) VALUES ('6209', '', 'Egyéb információ-technológiai szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('63', 'H', 'Információs szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('631', 'H', 'Adatfeldolgozás, web-hoszting, világháló-portál szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('6311', '', 'Adatfeldolgozás, web-hoszting szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('6312', '', 'Világháló-portál szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('639', 'H', 'Egyéb információs szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('6391', '', 'Hírügynökségi tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('6399', '', 'Mns egyéb információs szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('641', 'H', 'Monetáris közvetítés');
INSERT INTO sic (code, sictype,description) VALUES ('6411', '', 'Jegybanki tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('6419', '', 'Egyéb monetáris közvetítés');
INSERT INTO sic (code, sictype,description) VALUES ('643', 'H', 'Befektetési alapok és hasonlók');
INSERT INTO sic (code, sictype,description) VALUES ('6430', '', 'Befektetési alapok és hasonlók');
INSERT INTO sic (code, sictype,description) VALUES ('649', 'H', 'Egyéb pénzügyi közvetítés');
INSERT INTO sic (code, sictype,description) VALUES ('6491', '', 'Pénzügyi lízing');
INSERT INTO sic (code, sictype,description) VALUES ('6492', '', 'Egyéb hitelnyújtás');
INSERT INTO sic (code, sictype,description) VALUES ('6499', '', 'Mns egyéb pénzügyi közvetítés');
INSERT INTO sic (code, sictype,description) VALUES ('651', 'H', 'Biztosítás');
INSERT INTO sic (code, sictype,description) VALUES ('6511', '', 'Életbiztosítás');
INSERT INTO sic (code, sictype,description) VALUES ('6512', '', 'Nem életbiztosítás');
INSERT INTO sic (code, sictype,description) VALUES ('652', 'H', 'Viszontbiztosítás');
INSERT INTO sic (code, sictype,description) VALUES ('6520', '', 'Viszontbiztosítás');
INSERT INTO sic (code, sictype,description) VALUES ('653', 'H', 'Nyugdíjalapok');
INSERT INTO sic (code, sictype,description) VALUES ('6530', '', 'Nyugdíjalapok');
INSERT INTO sic (code, sictype,description) VALUES ('66', 'H', 'Egyéb pénzügyi tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('6611', '', 'Pénz-, tőkepiac igazgatása');
INSERT INTO sic (code, sictype,description) VALUES ('6612', '', 'Értékpapír-, árutőzsdei ügynöki tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('6619', '', 'Egyéb pénzügyi kiegészítő tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('662', 'H', 'Biztosítást, nyugdíjalapot kiegészítő tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('6621', '', 'Kockázatértékelés, kárszakértés');
INSERT INTO sic (code, sictype,description) VALUES ('6622', '', 'Biztosítási ügynöki, brókeri tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('6629', '', 'Biztosítás, nyugdíjalap egyéb kiegészítő tevékenysége');
INSERT INTO sic (code, sictype,description) VALUES ('663', 'H', 'Alapkezelés');
INSERT INTO sic (code, sictype,description) VALUES ('6630', '', 'Alapkezelés');
INSERT INTO sic (code, sictype,description) VALUES ('68', 'H', 'Ingatlanügyletek');
INSERT INTO sic (code, sictype,description) VALUES ('681', 'H', 'Saját tulajdonú ingatlan adásvétele');
INSERT INTO sic (code, sictype,description) VALUES ('6810', '', 'Saját tulajdonú ingatlan adásvétele');
INSERT INTO sic (code, sictype,description) VALUES ('682', 'H', 'Saját tulajdonú, bérelt ingatlan bérbeadása, üzemeltetése');
INSERT INTO sic (code, sictype,description) VALUES ('6820', '', 'Saját tulajdonú, bérelt ingatlan bérbeadása, üzemeltetése');
INSERT INTO sic (code, sictype,description) VALUES ('683', 'H', 'Ingatlanügynöki, -kezelési szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('6831', '', 'Ingatlanügynöki tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('6832', '', 'Ingatlankezelés');
INSERT INTO sic (code, sictype,description) VALUES ('69', 'H', 'Jogi, számviteli, adószakértői tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('691', 'H', 'Jogi tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('6910', '', 'Jogi tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('692', 'H', 'Számviteli, könyvvizsgálói, adószakértői tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('6920', '', 'Számviteli, könyvvizsgálói, adószakértői tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('70', 'H', 'Üzletvezetési, vezetői tanácsadás');
INSERT INTO sic (code, sictype,description) VALUES ('701', 'H', 'Üzletvezetés');
INSERT INTO sic (code, sictype,description) VALUES ('7010', '', 'Üzletvezetés');
INSERT INTO sic (code, sictype,description) VALUES ('702', 'H', 'Üzletviteli tanácsadás');
INSERT INTO sic (code, sictype,description) VALUES ('7021', '', 'PR, kommunikáció');
INSERT INTO sic (code, sictype,description) VALUES ('7022', '', 'Üzletviteli, egyéb vezetési tanácsadás');
INSERT INTO sic (code, sictype,description) VALUES ('71', 'H', 'Építészmérnöki tevékenység; műszaki vizsgálat, elemzés');
INSERT INTO sic (code, sictype,description) VALUES ('711', 'H', 'Építészmérnöki tevékenység; műszaki vizsgálat, elemzés');
INSERT INTO sic (code, sictype,description) VALUES ('7111', '', 'Építészmérnöki tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('7112', '', 'Mérnöki tevékenység, műszaki tanácsadás');
INSERT INTO sic (code, sictype,description) VALUES ('712', 'H', 'Műszaki vizsgálat, elemzés');
INSERT INTO sic (code, sictype,description) VALUES ('7120', '', 'Műszaki vizsgálat, elemzés');
INSERT INTO sic (code, sictype,description) VALUES ('72', 'H', 'Tudományos kutatás, fejlesztés');
INSERT INTO sic (code, sictype,description) VALUES ('721', 'H', 'Természettudományi, műszaki kutatás, fejlesztés');
INSERT INTO sic (code, sictype,description) VALUES ('7211', '', 'Biotechnológiai kutatás, fejlesztés');
INSERT INTO sic (code, sictype,description) VALUES ('7219', '', 'Egyéb természettudományi, műszaki kutatás, fejlesztés');
INSERT INTO sic (code, sictype,description) VALUES ('722', 'H', 'Társadalomtudományi, humán kutatás, fejlesztés');
INSERT INTO sic (code, sictype,description) VALUES ('7220', '', 'Társadalomtudományi, humán kutatás, fejlesztés');
INSERT INTO sic (code, sictype,description) VALUES ('73', 'H', 'Reklám, piackutatás');
INSERT INTO sic (code, sictype,description) VALUES ('731', 'H', 'Reklám');
INSERT INTO sic (code, sictype,description) VALUES ('7311', '', 'Reklámügynöki tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('7312', '', 'Médiareklám');
INSERT INTO sic (code, sictype,description) VALUES ('732', 'H', 'Piac-, közvélemény-kutatás');
INSERT INTO sic (code, sictype,description) VALUES ('7320', '', 'Piac-, közvélemény-kutatás');
INSERT INTO sic (code, sictype,description) VALUES ('74', 'H', 'Egyéb szakmai, tudományos, műszaki tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('741', 'H', 'Divat-, formatervezés');
INSERT INTO sic (code, sictype,description) VALUES ('7410', '', 'Divat-, formatervezés');
INSERT INTO sic (code, sictype,description) VALUES ('742', 'H', 'Fényképészet');
INSERT INTO sic (code, sictype,description) VALUES ('7420', '', 'Fényképészet');
INSERT INTO sic (code, sictype,description) VALUES ('743', 'H', 'Fordítás, tolmácsolás');
INSERT INTO sic (code, sictype,description) VALUES ('7430', '', 'Fordítás, tolmácsolás');
INSERT INTO sic (code, sictype,description) VALUES ('749', 'H', 'Mns egyéb szakmai, tudományos, műszaki tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('7490', '', 'Mns egyéb szakmai, tudományos, műszaki tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('75', 'H', 'Állat-egészségügyi ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('750', 'H', 'Állat-egészségügyi ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('7500', '', 'Állat-egészségügyi ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('77', 'H', 'Kölcsönzés, operatív lízing');
INSERT INTO sic (code, sictype,description) VALUES ('771', 'H', 'Gépjárműkölcsönzés');
INSERT INTO sic (code, sictype,description) VALUES ('7711', '', 'Személygépjármű kölcsönzése');
INSERT INTO sic (code, sictype,description) VALUES ('772', 'H', 'Személyi használatú, háztartási cikk kölcsönzése');
INSERT INTO sic (code, sictype,description) VALUES ('7721', '', 'Szabadidős, sporteszköz kölcsönzése');
INSERT INTO sic (code, sictype,description) VALUES ('7722', '', 'Videokazetta, lemez kölcsönzése');
INSERT INTO sic (code, sictype,description) VALUES ('7729', '', 'Egyéb személyi használatú, háztartási cikk kölcsönzése');
INSERT INTO sic (code, sictype,description) VALUES ('773', 'H', 'Egyéb gép, tárgyi eszköz kölcsönzése');
INSERT INTO sic (code, sictype,description) VALUES ('7731', '', 'Mezőgazdasági gép kölcsönzése');
INSERT INTO sic (code, sictype,description) VALUES ('7732', '', 'Építőipari gép kölcsönzése');
INSERT INTO sic (code, sictype,description) VALUES ('7734', '', 'Vízi szállítóeszköz kölcsönzése');
INSERT INTO sic (code, sictype,description) VALUES ('7735', '', 'Légi szállítóeszköz kölcsönzése');
INSERT INTO sic (code, sictype,description) VALUES ('7739', '', 'Egyéb gép, tárgyi eszköz kölcsönzése');
INSERT INTO sic (code, sictype,description) VALUES ('774', 'H', 'Immateriális javak kölcsönzése');
INSERT INTO sic (code, sictype,description) VALUES ('7740', '', 'Immateriális javak kölcsönzése');
INSERT INTO sic (code, sictype,description) VALUES ('78', 'H', 'Munkaerőpiaci szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('781', 'H', 'Munkaközvetítés');
INSERT INTO sic (code, sictype,description) VALUES ('7810', '', 'Munkaközvetítés');
INSERT INTO sic (code, sictype,description) VALUES ('782', 'H', 'Munkaerőkölcsönzés');
INSERT INTO sic (code, sictype,description) VALUES ('7820', '', 'Munkaerőkölcsönzés');
INSERT INTO sic (code, sictype,description) VALUES ('783', 'H', 'Egyéb emberierőforrás-ellátás, -gazdálkodás');
INSERT INTO sic (code, sictype,description) VALUES ('7830', '', 'Egyéb emberierőforrás-ellátás, -gazdálkodás');
INSERT INTO sic (code, sictype,description) VALUES ('79', 'H', 'Utazásközvetítés, utazásszervezés, egyéb foglalás');
INSERT INTO sic (code, sictype,description) VALUES ('791', 'H', 'Utazásközvetítés, utazásszervezés');
INSERT INTO sic (code, sictype,description) VALUES ('7911', '', 'Utazásközvetítés');
INSERT INTO sic (code, sictype,description) VALUES ('7912', '', 'Utazásszervezés');
INSERT INTO sic (code, sictype,description) VALUES ('799', 'H', 'Egyéb foglalás');
INSERT INTO sic (code, sictype,description) VALUES ('7990', '', 'Egyéb foglalás');
INSERT INTO sic (code, sictype,description) VALUES ('80', 'H', 'Biztonsági, nyomozói tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('801', 'H', 'Személybiztonsági tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('8010', '', 'Személybiztonsági tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('802', 'H', 'Biztonsági rendszer szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('8020', '', 'Biztonsági rendszer szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('803', 'H', 'Nyomozás');
INSERT INTO sic (code, sictype,description) VALUES ('8030', '', 'Nyomozás');
INSERT INTO sic (code, sictype,description) VALUES ('81', 'H', 'Építményüzemeltetés, zöldterület-kezelés');
INSERT INTO sic (code, sictype,description) VALUES ('811', 'H', 'Építményüzemeltetés');
INSERT INTO sic (code, sictype,description) VALUES ('8110', '', 'Építményüzemeltetés');
INSERT INTO sic (code, sictype,description) VALUES ('812', 'H', 'Takarítás');
INSERT INTO sic (code, sictype,description) VALUES ('8121', '', 'Általános épülettakarítás');
INSERT INTO sic (code, sictype,description) VALUES ('8122', '', 'Egyéb épület-, ipari takarítás');
INSERT INTO sic (code, sictype,description) VALUES ('8129', '', 'Egyéb takarítás');
INSERT INTO sic (code, sictype,description) VALUES ('813', 'H', 'Zöldterület-kezelés');
INSERT INTO sic (code, sictype,description) VALUES ('8130', '', 'Zöldterület-kezelés');
INSERT INTO sic (code, sictype,description) VALUES ('82', 'H', 'Adminisztratív, kiegészítő egyéb üzleti szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('821', 'H', 'Adminisztratív, kiegészítő szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('8211', '', 'Összetett adminisztratív szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('8219', '', 'Fénymásolás, egyéb irodai szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('822', 'H', 'Telefoninformáció');
INSERT INTO sic (code, sictype,description) VALUES ('8220', '', 'Telefoninformáció');
INSERT INTO sic (code, sictype,description) VALUES ('823', 'H', 'Konferencia, kereskedelmi bemutató szervezése');
INSERT INTO sic (code, sictype,description) VALUES ('8230', '', 'Konferencia, kereskedelmi bemutató szervezése');
INSERT INTO sic (code, sictype,description) VALUES ('829', 'H', 'Egyéb kiegészítő gazdasági tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('8291', '', 'Követelésbehajtás');
INSERT INTO sic (code, sictype,description) VALUES ('8292', '', 'Csomagolás');
INSERT INTO sic (code, sictype,description) VALUES ('8299', '', 'Mns egyéb kiegészítő üzleti szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('84', 'H', 'Közigazgatás, védelem; kötelező társadalombiztosítás');
INSERT INTO sic (code, sictype,description) VALUES ('841', 'H', 'Közigazgatás');
INSERT INTO sic (code, sictype,description) VALUES ('8411', '', 'Általános közigazgatás');
INSERT INTO sic (code, sictype,description) VALUES ('8413', '', 'Üzleti élet szabályozása, hatékonyságának ösztönzése');
INSERT INTO sic (code, sictype,description) VALUES ('842', 'H', 'Társadalmi közszolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('8421', '', 'Külügyek');
INSERT INTO sic (code, sictype,description) VALUES ('8422', '', 'Honvédelem');
INSERT INTO sic (code, sictype,description) VALUES ('8423', '', 'Igazságügy, bíróság');
INSERT INTO sic (code, sictype,description) VALUES ('8424', '', 'Közbiztonság, közrend');
INSERT INTO sic (code, sictype,description) VALUES ('8425', '', 'Tűzvédelem');
INSERT INTO sic (code, sictype,description) VALUES ('843', 'H', 'Kötelező társadalombiztosítás');
INSERT INTO sic (code, sictype,description) VALUES ('8430', '', 'Kötelező társadalombiztosítás');
INSERT INTO sic (code, sictype,description) VALUES ('85', 'H', 'Oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('851', 'H', 'Iskolai előkészítő oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('8510', '', 'Iskolai előkészítő oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('852', 'H', 'Alapfokú oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('8520', '', 'Alapfokú oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('853', 'H', 'Középfokú oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('8531', '', 'Általános középfokú oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('8532', '', 'Szakmai középfokú oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('854', 'H', 'Felső szintű oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('8541', '', 'Felső szintű, nem felsőfokú oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('8542', '', 'Felsőfokú oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('855', 'H', 'Egyéb oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('8551', '', 'Sport, szabadidős képzés');
INSERT INTO sic (code, sictype,description) VALUES ('8552', '', 'Kulturális képzés');
INSERT INTO sic (code, sictype,description) VALUES ('8553', '', 'Járművezető-oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('8559', '', 'Mns egyéb oktatás');
INSERT INTO sic (code, sictype,description) VALUES ('856', 'H', 'Oktatást kiegészítő tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('8560', '', 'Oktatást kiegészítő tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('86', 'H', 'Humán-egészségügyi ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('861', 'H', 'Fekvőbeteg-ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('8610', '', 'Fekvőbeteg-ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('862', 'H', 'Járóbeteg-ellátás, fogorvosi ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('8621', '', 'Általános járóbeteg-ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('8622', '', 'Szakorvosi járóbeteg-ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('8623', '', 'Fogorvosi járóbeteg-ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('869', 'H', 'Egyéb humán-egészségügyi ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('8690', '', 'Egyéb humán-egészségügyi ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('87', 'H', 'Bentlakásos, nem kórházi ápolás');
INSERT INTO sic (code, sictype,description) VALUES ('871', 'H', 'Bentlakásos, nem kórházi ápolás');
INSERT INTO sic (code, sictype,description) VALUES ('8710', '', 'Bentlakásos, nem kórházi ápolás');
INSERT INTO sic (code, sictype,description) VALUES ('872', 'H', 'Mentális, szenvedélybeteg bentlakásos ellátása');
INSERT INTO sic (code, sictype,description) VALUES ('8720', '', 'Mentális, szenvedélybeteg bentlakásos ellátása');
INSERT INTO sic (code, sictype,description) VALUES ('873', 'H', 'Idősek, fogyatékosok bentlakásos ellátása');
INSERT INTO sic (code, sictype,description) VALUES ('8730', '', 'Idősek, fogyatékosok bentlakásos ellátása');
INSERT INTO sic (code, sictype,description) VALUES ('879', 'H', 'Egyéb bentlakásos ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('8790', '', 'Egyéb bentlakásos ellátás');
INSERT INTO sic (code, sictype,description) VALUES ('88', 'H', 'Szociális ellátás bentlakás nélkül');
INSERT INTO sic (code, sictype,description) VALUES ('881', 'H', 'Idősek, fogyatékosok szociális ellátása bentlakás nélkül');
INSERT INTO sic (code, sictype,description) VALUES ('8810', '', 'Idősek, fogyatékosok szociális ellátása bentlakás nélkül');
INSERT INTO sic (code, sictype,description) VALUES ('889', 'H', 'Egyéb szociális ellátás bentlakás nélkül');
INSERT INTO sic (code, sictype,description) VALUES ('8891', '', 'Gyermekek napközbeni ellátása');
INSERT INTO sic (code, sictype,description) VALUES ('8899', '', 'Mns egyéb szociális ellátás bentlakás nélkül');
INSERT INTO sic (code, sictype,description) VALUES ('90', 'H', 'Alkotó-, művészeti, szórakoztató tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('900', 'H', 'Alkotó-, művészeti, szórakoztató tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('9001', '', 'Előadó-művészet');
INSERT INTO sic (code, sictype,description) VALUES ('9002', '', 'Előadó-művészetet kiegészítő tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('9003', '', 'Alkotóművészet');
INSERT INTO sic (code, sictype,description) VALUES ('9004', '', 'Művészeti létesítmények működtetése');
INSERT INTO sic (code, sictype,description) VALUES ('91', 'H', 'Könyvtári, levéltári, múzeumi, egyéb kulturális tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('910', 'H', 'Könyvtári, levéltári, múzeumi, egyéb kulturális tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('9101', '', 'Könyvtári, levéltári tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('9102', '', 'Múzeumi tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('9103', '', 'Történelmi hely, építmény, egyéb látványosság működtetése');
INSERT INTO sic (code, sictype,description) VALUES ('9104', '', 'Növény-, állatkert, természetvédelmi terület működtetése');
INSERT INTO sic (code, sictype,description) VALUES ('92', 'H', 'Szerencsejáték, fogadás');
INSERT INTO sic (code, sictype,description) VALUES ('920', 'H', 'Szerencsejáték, fogadás');
INSERT INTO sic (code, sictype,description) VALUES ('9200', '', 'Szerencsejáték, fogadás');
INSERT INTO sic (code, sictype,description) VALUES ('93', 'H', 'Sport-, szórakoztató, szabadidős tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('931', 'H', 'Sporttevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('9311', '', 'Sportlétesítmény működtetése');
INSERT INTO sic (code, sictype,description) VALUES ('9312', '', 'Sportegyesületi tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('9313', '', 'Testedzési szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('9319', '', 'Egyéb sporttevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('932', 'H', 'Egyéb szórakoztatás, szabadidős tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('9321', '', 'Vidámparki, szórakoztatóparki tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('9329', '', 'Mns egyéb szórakoztatás, szabadidős tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('94', 'H', 'Érdekképviselet');
INSERT INTO sic (code, sictype,description) VALUES ('941', 'H', 'Vállalkozói, szakmai érdekképviselet');
INSERT INTO sic (code, sictype,description) VALUES ('9411', '', 'Vállalkozói, munkaadói érdekképviselet');
INSERT INTO sic (code, sictype,description) VALUES ('9412', '', 'Szakmai érdekképviselet');
INSERT INTO sic (code, sictype,description) VALUES ('942', 'H', 'Szakszervezeti tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('9420', '', 'Szakszervezeti tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('949', 'H', 'Egyéb közösségi, társadalmi tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('9491', '', 'Egyházi tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('9492', '', 'Politikai tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('9499', '', 'Mns egyéb közösségi, társadalmi tevékenység');
INSERT INTO sic (code, sictype,description) VALUES ('95', 'H', 'Számítógép, személyi, háztartási cikk javítása');
INSERT INTO sic (code, sictype,description) VALUES ('951', 'H', 'Számítógép, kommunikációs eszköz javítása');
INSERT INTO sic (code, sictype,description) VALUES ('9511', '', 'Számítógép, -periféria javítása');
INSERT INTO sic (code, sictype,description) VALUES ('9512', '', 'Kommunikációs eszköz javítása');
INSERT INTO sic (code, sictype,description) VALUES ('952', 'H', 'Személyi, háztartási cikk javítása');
INSERT INTO sic (code, sictype,description) VALUES ('9521', '', 'Szórakoztatóelektronikai cikk javítása');
INSERT INTO sic (code, sictype,description) VALUES ('9522', '', 'Háztartási gép, háztartási, kerti eszköz javítása');
INSERT INTO sic (code, sictype,description) VALUES ('9523', '', 'Lábbeli, egyéb bőráru javítása');
INSERT INTO sic (code, sictype,description) VALUES ('9524', '', 'Bútor, lakberendezési tárgy javítása');
INSERT INTO sic (code, sictype,description) VALUES ('9525', '', 'Óra-, ékszerjavítás');
INSERT INTO sic (code, sictype,description) VALUES ('9529', '', 'Egyéb személyi, háztartási cikk javítása');
INSERT INTO sic (code, sictype,description) VALUES ('96', 'H', 'Egyéb személyi szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('960', 'H', 'Egyéb személyi szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('9601', '', 'Textil, szőrme mosása, tisztítása');
INSERT INTO sic (code, sictype,description) VALUES ('9602', '', 'Fodrászat, szépségápolás');
INSERT INTO sic (code, sictype,description) VALUES ('9603', '', 'Temetkezés, temetkezést kiegészítő szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('9604', '', 'Fizikai közérzetet javító szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('9609', '', 'Mns egyéb személyi szolgáltatás');
INSERT INTO sic (code, sictype,description) VALUES ('97', 'H', 'Háztartási alkalmazottat foglalkoztató magánháztartás');
INSERT INTO sic (code, sictype,description) VALUES ('970', 'H', 'Háztartási alkalmazottat foglalkoztató magánháztartás');
INSERT INTO sic (code, sictype,description) VALUES ('9700', '', 'Háztartási alkalmazottat foglalkoztató magánháztartás');
INSERT INTO sic (code, sictype,description) VALUES ('98', 'H', 'Háztartás termék-előállítása, szolgáltatása saját fogyasztásra');
INSERT INTO sic (code, sictype,description) VALUES ('981', 'H', 'Háztartás termék-előállítása, szolgáltatása saját fogyasztásra');
INSERT INTO sic (code, sictype,description) VALUES ('9810', '', 'Háztartás termék-előállítása, szolgáltatása saját fogyasztásra');
INSERT INTO sic (code, sictype,description) VALUES ('982', 'H', 'Háztartás szolgáltatása saját fogyasztásra');
INSERT INTO sic (code, sictype,description) VALUES ('9820', '', 'Háztartás szolgáltatása saját fogyasztásra');
INSERT INTO sic (code, sictype,description) VALUES ('99', 'H', 'Területen kívüli szervezet');
INSERT INTO sic (code, sictype,description) VALUES ('990', 'H', 'Területen kívüli szervezet');
INSERT INTO sic (code, sictype,description) VALUES ('9900', '', 'Területen kívüli szervezet');
commit;
